components:
  examples: {}
  headers: {}
  parameters: {}
  requestBodies: {}
  responses: {}
  schemas:
Transfer:
  type: object
    properties:
    id:
      type: string
    transferType:
      $ref: '#/components/schemas/TransferType'
    shipmentIds:
      description: list of Shipment ids
      type: array
      items:
        type: integer
    createdAt:
      type: string
      format: date-time
    updatedAt:
      type: string
      format: date-time
    status:
      $ref: '#/components/schemas/TransferStatus'
Shipment:
  type: object
  properties:
    id:
      type: string
    origin:
      $ref: '#/components/schemas/Location'
    destination:
      $ref: '#/components/schemas/Location'
    products:
      description: list of Product ids
      type: array
      items:
        type: integer
    box_labels_url:
      type: string
    pallet_labels_url:
      type: string
    shipment_type:
      $ref: '#/components/schemas/ShipmentType'
    content:
      $ref: '#/components/schemas/ShipmentContent'
    expected_pickup:
      type: string
      format: date-time
    actual_pickup:
      type: string
      format: date-time
    carrier:
      type: string
    shipmentStatus:
      $ref: '#/components/schemas/ShipmentStatus'
Carrier:
  type: object
  properties:
    id:
      type: string
    businessInfo:
      $ref: '#/components/schemas/BusinessInfo'
      type: BusinessInfo
    website:
      type: string
    buisnessContacts:
      type: array
      items:
        $ref: '#/components/schemas/BusinessContact'
    services:
      $ref: '#/components/schemas/ServiceType'
    active_since:
      type: string
      format: date-time
    scac:
      description: 4 characters (see [Wikipedia](https://en.wikipedia.org/wiki/Standard_Carrier_Alpha_Code), needed for the BOL)
      type: string
BusinessContact:
  type: object
  properties:
    id:
      type: string
    name:
      type: string
    general:
      type: object
      properties:
        emails:
          description: list of emails
          type: array
          items:
            type: Object
            properties:
              buisnessUnit:
                type: string
              email:
                type: string
        addresses:
          description: list of addresses
          type: array
          items:
            $ref: '#/components/schemas/Location'
    phones:
      discription: list of phones
      type: array
      items:
        type: Object
        properties:
          contactName:
            type: string
          phoneNumber:
            type: string
    emails:
      description: list of emails
      type: array
      items:
        type: Object
        properties:
          name:
            type: string
          address:
            type: string
    addresses:
      description: list of addresses
      type: array
      items:
        $ref: '#/components/schemas/Location'
Product:
  type: object
  properties:
    id:
      discription: DSKU
      type: string
    sku:
      type: string
    fnsku:
      type: string
    msku:
      type: string
    upc:
      type: string
    ean:
      type: string
    dimensions:
      type: object
      properties:
        length:
          type: integer
        width:
          type: integer
        height:
          type: integer
        units:
          $ref: '#/components/schemas/DimensionsUnits'
        weight:
          $ref: '#/components/schemas/WeightUnits'
Location:
  type: object
  properties:
    id:
      type: string
    title:
      type: string
    address:
      type: object
      properties:
        line1:
          type: string
        line2:
          type: string
        city:
          type: string
        zip:
          type: string
        state:
          type: string
        country:
          type: string
Notification:
  type: object
  properties:
    id:
      type: string
    created:
      type: string
      format: date-time
    destination:
      type: <resource_uri>
    origin:
      type: <resource_uri>
    type:
      type: ‘info’ | ‘alert’
ShipmentContent:
  type: object
  properties:
    num_pallets:
      type: number
    num_boxes:
      type: number
ServiceType:
  type: string
  enum:
    - PARCEL
    - LTL
    - FL
TransferStatus:
  type:
  enum:
    - draft
    - in progress
    - complete
    - cancelled
TransferType:
  type:
    enum:
      - ‘AMAZON_FULLFILMENT’
ShipmentStatus:
  type:
  enum:
    - draft
    - requested
    - ready for pickup
    - scheduled
    - shipped
    - arrived at destination
DimensionsUnits:
  type:
  enum:
    - ‘m’
    - ‘cm’
    - ‘inch’
    - ‘in’
    - ‘ft’
Weight:
  type: object
  properties:
    value:
      type: number
      minimum: 0
    units:
      $ref: '#/components/schemas/WeightUnits'
WeightUnits:
  type:
  enum:
    - g
    - kg
    - ounce
    - lb
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      name: auth
      in: query
    basicAuth:
      scheme: basic
      type: http
    oAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.deliverr.com/oauth/v1/authorize'
          tokenUrl: 'https://api.deliverr.com/oauth/v1/token'
          scopes:
            read: Read access to your account
            write: Write access to your account
info:
  title: fba farwarding
  version: 1.0.0
  description: this is the public api tosa of deliverr
  license:
    name: MGE
  contact:
    name: gal
openapi: 3.0.0
paths:
  /inventory/storage/:
    get: null
  /products:
    get: null
  /transfers:
    get: null
  '/tranfers/{transferId}':
    get: null
    delete: null
  /tranfers:
    post: null
  '/transfers/{transferId}/{field}':
    put: null
  '/shipments/?{transferId}':
    get: null
  '/shipments/{shipmentId}':
    get: null
    delete: null
  /carriers/:
    get: null
  '/carriers?shipmentId={shipmentId}':
    get: null
  /carriers:
    post: null
  '/carriers/{carrierId}':
    delete: null
  '/pricer/estimate-shipment/{shipmentId}':
    get: null
  '/pricer/estimate-transfer/{transferId}':
    get: null
  /pricer/price-list:
    get: null
  '/transfer-tracker/tracke-shipment/{shipmentId}':
    get: null
  '/transfer-tracker/track-transfer/{transferId}':
    get: null
servers:
  - url: 'http://localhost:3000'
    description: Local development
  - url: 'https://api.deliverr.com'
    description: Prod development
